// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql"
)

type Blog struct {
	ID      int32        `json:"id"`
	Title   string       `json:"title"`
	Content string       `json:"content"`
	UserID  int32        `json:"user_id"`
	Created sql.NullTime `json:"created"`
	Updated sql.NullTime `json:"updated"`
}

type User struct {
	ID       int32        `json:"id"`
	Username string       `json:"username"`
	Email    string       `json:"email"`
	Password string       `json:"password"`
	Created  sql.NullTime `json:"created"`
	Updated  sql.NullTime `json:"updated"`
}
